/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.CurrentSesionController;
import controllers.UserController;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Carlos Andres
 */
public class UserView extends javax.swing.JFrame {
    /* botones */
    
    private int userIdLogged; //id del usuario logueado
    private Object[][] rows;
    private UserController ctrlUser = new UserController();
    private CHAFDependenciesViews dp = new CHAFDependenciesViews ();
     /**
     * Creates new form UsuariosView
     */
    public UserView() {
        
    initComponents();
    this.setResizable(false);
    }
    
    public void refresh(){
        this.initComponents();
    }
    
    public void setUserIdLogged(int id){
      this.userIdLogged = id;
    }
    public void setCurrentUserName(String name){
       this.nameUser.setText(name);
    }
    
    public void setCurrentUserRol(String rol){
        this.rolUser.setText(rol);
    }
    
    public Object[][] initRows(int filas){
     //// variables para traer el login del usuario, 
     ///  ya que el metodo getUserForTable pide como parametros
     ///  el indice de la columna de la consulta y un iterador
     /**/ int loginUserOnConsult = 0;
     /**/ int nameUserOnConsult = 1;
     this.rows = new Object[filas][5];
     for(int i = 0;i < filas;i++){
         for(int j = 0;j< 5 ;j++){
            switch(j){
                    case 0: rows[i][j] = this.ctrlUser.getUserForTable(loginUserOnConsult, i);
                    break;
                    case 1: rows[i][j] = this.ctrlUser.getUserForTable(nameUserOnConsult, i);
                    break;    
                    case 2: rows[i][j] = this.dp.getEditar();
                    break;
                    case 3: rows[i][j] = this.dp.getEliminar();
                    break;
                    case 4: rows[i][j] = this.dp.getActivar();
                    break;                   
            }
         }
     }
     return rows;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        materialButton1 = new libraries.MaterialButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FechaActual = new javax.swing.JLabel();
        rolUser = new javax.swing.JLabel();
        nameUser = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        materialButton1.setBackground(new java.awt.Color(119, 177, 236));
        materialButton1.setText("Registrar Usuario");
        materialButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButton1MouseClicked(evt);
            }
        });
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            initRows(this.ctrlUser.getUsersOnTable())
            ,
            new String [] {
                "Usuario", "Nombre", "Editar","Desactivar","Activar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

        });
        this.jTable1.getColumn("Editar").setCellRenderer(this.dp.getRender());
        this.jTable1.getColumn("Editar").setMaxWidth(this.dp.getSizeColumn());
        this.jTable1.getColumn("Desactivar").setCellRenderer(this.dp.getRender());
        this.jTable1.getColumn("Desactivar").setMaxWidth(this.dp.getSizeColumn() + 20);
        this.jTable1.getColumn("Activar").setCellRenderer(this.dp.getRender());
        this.jTable1.getColumn("Activar").setMaxWidth(this.dp.getSizeColumn());
        this.jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        FechaActual.setText(this.dp.getFechaActual());

        rolUser.setText("jLabel2");

        nameUser.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rolUser)
                    .addComponent(nameUser)
                    .addComponent(FechaActual)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(materialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(FechaActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rolUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("[UserView]: entrando a creacion de Usuarios");
        TercerosRegisterView creacionTercero = new TercerosRegisterView("USUARIO",0,null,null,this);
        creacionTercero.setVisible(true);
        creacionTercero.setLayout(null);
        creacionTercero.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
    }//GEN-LAST:event_materialButton1ActionPerformed

    private void materialButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButton1MouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_materialButton1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = this.jTable1.getSelectedRow();
        int col = this.jTable1.getSelectedColumn();     
        
        switch(col){
            case 2:{
                System.out.println("col == 3 row ="+row);
                TercerosRegisterView creacionTercero = new TercerosRegisterView("USUARIO",1,null,null,this);
                Object id = this.jTable1.getModel().getValueAt(row, 0);
                ArrayList <String> datos = this.ctrlUser.showRegisterUser(id.toString());
                creacionTercero.setNumeroIdentificacion(datos.get(1));
                creacionTercero.setUserDir(datos.get(2));
                creacionTercero.setNombreUser(datos.get(3));
                creacionTercero.setTelUser(datos.get(4));
                creacionTercero.setVisible(true);                    
            }
            break;
            case 3:{
            // Boton  Desactivar
                Object id = this.jTable1.getModel().getValueAt(row, 0);
                if(this.ctrlUser.getEstadoUser(id.toString())){
                    this.ctrlUser.cambiarEstado(id.toString(),false);
                    JOptionPane.showMessageDialog(this,"Se Inactivo satisfactoriamente");
                }else{
                    JOptionPane.showMessageDialog(this,"Usuario ya se encuentra Inactivo");
                }
            }
            break;
            case 4:{
            // Boton  Activar
                Object id = this.jTable1.getModel().getValueAt(row, 0);
                if(this.ctrlUser.getEstadoUser(id.toString())){
                    JOptionPane.showMessageDialog(this,"Usuario ya se encuentra Activo");
                }else{
                    this.ctrlUser.cambiarEstado(id.toString(),true);
                    JOptionPane.showMessageDialog(this,"Se Activo satisfactoriamente");
                }
            }
            break;
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
     
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaActual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private libraries.MaterialButton materialButton1;
    private javax.swing.JLabel nameUser;
    private javax.swing.JLabel rolUser;
    // End of variables declaration//GEN-END:variables
}
